version: "0.1.0" # Schema Version

name: "Shambhala 2024"
startDate: 7/26/24
endDate: 7/29/24
iconImageURL: "https://firebasestorage.googleapis.com/v0/b/festivl.appspot.com/o/userContent%2Flogo_small.png?alt=media&token=7766fa90-6591-4e25-92b4-2ff354cb970d"
siteMapImageURL: "https://firebasestorage.googleapis.com/v0/b/festivl.appspot.com/o/userContent%2FShambhala-Map.png?alt=media&token=01ec8e02-7e31-4ae7-a91b-ab92dbee6894"
address: "Salmo River Ranch, 7790 Hwy 3, Salmo, BC, V0G 1Z0, Canada"
timeZone: "America/Denver"

# Colors
colorScheme:
  primaryColor: 0xFF5733
  workshopsColor: 0xC70039

contact-info:
- phoneNumber: "1-778-724-1119"
  title: "SOS Number"
  description: "This number will get you any one or all of our highly trained Medical, Fire Response, Security or Harm Reduction Teams."

stages:
- name: "Ampitheatre"
  color: 0xdf529f
  iconImageURL: "https://firebasestorage.googleapis.com/v0/b/festivl.appspot.com/o/userContent%2Fstage_logo_amp.png?alt=media&token=259c79a0-0df8-4434-931a-e3b9037789a6"
  
- name: "Fractal Forest"
  color: 0xbabc69
  iconImageURL: "https://firebasestorage.googleapis.com/v0/b/festivl.appspot.com/o/userContent%2Fstage_logo_fractal.png?alt=media&token=fc4b8549-b689-4b90-88d6-e318d8db6e4a"
  
- name: "Grove"
  color: 0x77bd91
  iconImageURL: "https://firebasestorage.googleapis.com/v0/b/festivl.appspot.com/o/userContent%2Fstage_logo_grove.png?alt=media&token=514a6eca-079f-45cf-8ccf-1decba72b35d"

- name: "Living Room"
  color: 0x7cb8af
  iconImageURL: "https://firebasestorage.googleapis.com/v0/b/festivl.appspot.com/o/userContent%2Fstage_logo_living_room.png?alt=media&token=3985d60a-e4de-4c76-aa3b-86fa53eaeece"

- name: "Pagoda"
  color: 0x3e71b0
  iconImageURL: "https://firebasestorage.googleapis.com/v0/b/festivl.appspot.com/o/userContent%2Fstage_logo_pagoda.png?alt=media&token=c33da197-c0bd-4f4d-8c79-8fd53c5b8297"

- name: "Village"
  color: 0x8379b2
  iconImageURL: "https://firebasestorage.googleapis.com/v0/b/festivl.appspot.com/o/userContent%2Fstage_logo_village.png?alt=media&token=257453e1-04a1-40f5-af5f-5017a874a7f7"

- name: "Secret Garden"
  color: 0x136836
  iconImageURL: "http://example.com/tranquil-meadow.jpg"
